### ISSUE TITLE
[proposal] Changelog handling process

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#435]
Keeping up to date the changelog file is a time consuming operation as to prevent conflicts we do it only when creating a release. In this way documenting all the changes requires to go through pull requests and issues to find what has been changed and to figure out if requires to be documented in the changelog. 

**proposal**

To reduce the time required for the operation we could have a folder containing small files describing the change made in each pull request with a message, the number of the pull request and the issue, the author if is a contributor and the type of change performed (according to [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)).

An example of file could be:

```yaml
# saved in changelogs/unreleased/400-document-a-change
title: "Document a change"
merge_request: 400
author: @manfred
type: added
```

All the files can live in a folder, e.g. `changelogs/unreleased` and be named with the pull request number followed by the slug of the title. In this way chances that two pull requests generates a conflict should be almost zero.

Before release we get the file contents and assemble the changelog format. Once done all small files will be removed.

To ensure that only changes scheduled for the release are merged I would do the release process on a separate branch named against the `major.minor` version. For example for release 0.32.0 this process should be done on a branch named `0.32`. After each release we merge the changes related to the changelog in `master` so to keep it updated.

**Comment by avvertix** [comment]
@giacolos what you think?

**Comment by giacolos** [comment]
@avvertix I think this is something we need and I agree that we should do it to better manage the process. 
I would also include in the release note a reference to the corresponding issue, specifically the corresponding user history. The rationale behind this is to make the non-technical stakeholders of the OS project able to catch the innovation of the new release at a glance.

**Comment by avvertix** [comment]
Good, then let's have the issue number inside the small file so it can be used

```yaml
# saved in changelogs/unreleased/400-document-a-change
title: "Document a change"
issue: 380
merge_request: 400
author: @manfred
type: added
```
